# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MDLlJpCjzWN5CusHBBOndIqpDCB85d3m
"""

from google.colab import files
upload = files.upload()

import pandas as pd
import numpy as np
# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Clustering
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Hierarchical clustering
from scipy.cluster.hierarchy import dendrogram, linkage

df = pd.read_csv("clients2.csv")
df.head()
df.info()

# Remove duplicates
df.drop_duplicates(inplace=True)

# Handle missing values
df.fillna(method='ffill', inplace=True)

# Handle missing values
df.isnull().sum()

# Fill categorical with mode
for col in df.select_dtypes(include='object'):
    df[col].fillna(df[col].mode()[0], inplace=True)

# Fill numeric with median
for col in df.select_dtypes(include=np.number):
    df[col].fillna(df[col].median(), inplace=True)

# Convert correctly using format
df['date_of_birth'] = pd.to_datetime(
    df['date_of_birth'],
    format='%m-%d-%Y',
    errors='coerce'
)

# Create age
from datetime import datetime
current_year = datetime.now().year

df['age'] = current_year - df['date_of_birth'].dt.year

# Check nulls
#print("Null DOB:", df['date_of_birth'].isnull().sum())

#feature Engineering
#converts date_of_birth - age
#df['date_of_birth'] = df['date_of_birth'].astype(str)
#df['date_of_birth'] = pd.to_datetime(df['date_of_birth'], errors='coerce')
#df['age'] = 2026 - df['date_of_birth'].dt.year
#df['date_of_birth'].head()

#Feature Scaling
#Use StandardScaler or MinMaxScaler to normalize numeric variables -Scale Age & Satisfaction score
#client_ids = df['client_id']
from sklearn.preprocessing import StandardScaler
# Select only numeric columns (fixes the ValueError)
numeric_df = df.select_dtypes(include=['number'])


scaler = StandardScaler()
scaled_values = scaler.fit_transform(numeric_df)


from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters = 3 ,random_state=42)
df['cluster']= kmeans.fit_predict(scaled_values)
print(df[['client_id','cluster']].head())

print (df.columns)

print(df.dtypes)

numeric_df =df.select_dtypes(include=['int64','float64'])
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_data = scaler.fit_transform(numeric_df)

from sklearn.preprocessing import StandardScaler
numeric_df = df.select_dtypes(include='number')
scaler = StandardScaler()
scaled_data = scaler.fit_transform(numeric_df)

#df=df.drop('client_id',axis=1,errors='ignore')

print(df.select_dtypes(include='object').columns)

print(pd.DataFrame(scaled_data).isnull().sum())

df=df.fillna(df.median(numeric_only=True))

from sklearn.preprocessing import StandardScaler
numeric_df = df.select_dtypes(include='number')
scaler = StandardScaler()
scaled_data = scaler.fit_transform(numeric_df)

import numpy as np
print(np.isnan(scaled_data).sum())

#Find optimal cluster use Elbow method
from sklearn.cluster import KMeans
wcss = []

for i in range(1, 10):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit(scaled_data)
    wcss.append(kmeans.inertia_)

plt.plot(range(1, 10), wcss, marker='o')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.title('Elbow Method')
plt.show()

#Apply K-Means
kmeans = KMeans(n_clusters=4, random_state=42)
clusters = kmeans.fit_predict(scaled_data)

df['cluster'] = clusters

#SILHOUETTE SCORE
score = silhouette_score(scaled_data, clusters)
print("Silhouette Score:", score)

#Hierarchial Clustering
linked = linkage(scaled_data, method='ward')

plt.figure(figsize=(10, 6))
dendrogram(linked)
plt.title('Dendrogram')
plt.show()

df['Cluster_Name'] = df['cluster'].map({
    0: 'C1',
    1: 'C2',
    2: 'C3',
    3: 'C4'

})

cluster_summary = df.groupby('cluster').mean(numeric_only=True)

print(cluster_summary)

cluster_summary = df.groupby('Cluster_Name').mean(numeric_only=True)

print(cluster_summary)

Cluster_Name = {
    0: "Global Investors",
    1: "First-Time Buyers",
    2: "Corporate Buyers",
    3: "Luxury Investors"
}

df['segment'] = df['cluster'].map(Cluster_Name)

cluster_summary = df.groupby('segment').mean(numeric_only=True)

print(cluster_summary)

print(df.columns.tolist())



#Cluster distribution
#Visualisation
sns.countplot(x='segment', data=df)
plt.xticks(rotation=45)
plt.show()

#Age vs satisfaction
sns.scatterplot(x='age', y='satisfaction_score', hue='segment', data=df)
plt.show()

#Heat map
cluster_avg = df.groupby('cluster').mean(numeric_only=True)

sns.heatmap(cluster_avg, annot=True, cmap='coolwarm')
plt.title("Cluster Feature Comparison")
plt.show()

#Radarchart
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Select numeric features
features = ['age', 'satisfaction_score']   # use only columns YOU HAVE

# Step 2: Group by cluster
cluster_data = df.groupby('cluster')[features].mean()

# Step 3: Create angles
labels = features
num_vars = len(labels)

angles = np.linspace(0, 2*np.pi, num_vars, endpoint=False).tolist()

# CLOSE THE LOOP
angles += angles[:1]

# Step 4: Plot
plt.figure(figsize=(6,6))

for i in cluster_data.index:
    values = cluster_data.loc[i].tolist()

    # CLOSE THE LOOP
    values += values[:1]

    plt.polar(angles, values, label=f'Cluster {i}')

# Step 5: Add labels
plt.xticks(angles[:-1], labels)
plt.title("Radar Chart - Cluster Comparison")
plt.legend()
plt.show()

#Map
df['country'].value_counts().plot(kind='bar')
plt.title("Customers by Country")
plt.show()

average_score = df['satisfaction_score'].mean()

print("Average Satisfaction Score:", average_score)

average_score = round(df['satisfaction_score'].mean(), 2)

print("Average Satisfaction Score:", average_score)

print(
    df.groupby('cluster')['satisfaction_score'].mean()
)



df.to_csv('final_dataset_with_clusters.csv', index=False)

from google.colab import files
files.download('final_dataset_with_clusters.csv')